exports.getdistrictlist = (req, res) => {
  res.json({
    districtlist: [
      "Colombo",
      "Gampaha",
      "Kalutara",
      "Kandy",
      "Matale",
      "Nuwara Eliya",
      "Galle",
      "Matara",
      "Hambantota",
      "Jaffna",
      "Mannar",
      "Vauniya",
      "Mullativue",
      "Ampara",
      "Trincomalee",
      "Batticaloa",
      "Kilinochchi",
      "Kurunegala",
      "Puttalam",
      "Anuradhapura",
      "Polonnaruwa",
      "Badulla",
      "Moneragala",
      "Ratnapura",
      "Kegalle",
    ],
  });
};
